# Generated by Django 4.0.4 on 2022-05-06 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_teams_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['last_name']},
        ),
    ]
