# Generated by Django 4.0.4 on 2022-05-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_condition_alter_car_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='condition',
            field=models.CharField(choices=[('u', 'Used'), ('n', 'New'), ('r', 'Refurbished')], max_length=1),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('AT', 'Automatic'), ('MT', 'Manual'), ('AM', 'Automated Manual'), ('CVT', 'Continuosly Variable')], max_length=3),
        ),
    ]
