# Generated by Django 4.0.4 on 2022-05-07 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_condition_alter_car_transmission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['created_date']},
        ),
    ]
